export const POSTS = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/posts/post1.jpg",
    user: {
      username: "tunglam",
      profileImg: "/avatars/avatar1.jpg",
      fullName: "Thanh Tungg",
    },
    comments: [
      {
        _id: "1",
        text: "So beaty",
        user: {
          username: "janedoe",
          profileImg: "/avatars/avatar2.jpg",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "beemax",
      profileImg: "/avatars/avatar3.jpg",
      fullName: "Bee Max",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "longnt",
          profileImg: "/avatars/avatar3.jpg",
          fullName: "Long NT",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.jpeg",
    user: {
      username: "johndoe",
      profileImg: "/avatars/avatar5.jpg",
      fullName: "John Doe",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "Wow beaty 🤔",
    img: "/posts/post3.jpg",
    user: {
      username: "johndoe",
      profileImg: "/avatars/avatar5.jpg",
      fullName: "John Doe",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "janedoe",
          profileImg: "/avatars/avatar5.jpg",
          fullName: "Jane Doe",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Nguyen Long",
    username: "longnguyen",
    profileImg: "/avatars/avatar1.jpg",
  },
  {
    _id: "2",
    fullName: "Nguyen Tien Dat",
    username: "ddutj",
    profileImg: "/avatars/avatar2.jpg",
  },
  {
    _id: "3",
    fullName: "Manh Kien",
    username: "mkien",
    profileImg: "/avatars/avatar3.jpg",
  },
  {
    _id: "4",
    fullName: "Nam Tien",
    username: "namtien",
    profileImg: "/avatars/avatar4.jpg",
  },
  {
    _id: "5",
    fullName: "Nguyen Minh Hieu",
    username: "hieunm",
    profileImg: "/avatars/avatar5.jpg",
  },
  {
    _id: "5",
    fullName: "Bee Max",
    username: "beemax",
    profileImg: "/avatars/avatar6.jpg",
  },
];
